
import type { Metadata } from "next";
import { Inter } from "next/font/google"
import "./globals.css";
import Header from "./header";
import { useRef } from 'react';
import { Provider } from 'react-redux';
import store from '@/app/redux/store';
//import RouterChangeHandler from "@/app/utils/CheckAuthHandler"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
